---
- name: ensure cron job is installed
  cron:
    name: "{{ owncloud_vendor }} cron"
    cron_file: "{{ owncloud_vendor }}"
    user: apache
    minute: "*/15"
    job: "php -f {{ owncloud_destination }}/cron.php"