---
- name: ensure systemd service is installed
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/{{ owncloud_vendor }}.service"

- name: ensure systemd timer is installed
  template:
    src: systemd.timer.j2
    dest: "/etc/systemd/system/{{ owncloud_vendor }}.timer"

- name: ensure systemd timer is enabled
  service:
    name: "{{ owncloud_vendor }}.timer"
    state: started
    enabled: yes
