---
- name: ensure main directory has correct permissions
  file:
    path: /var/www/owncloud
    state: directory
    owner: root
    group: apache
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes
  when: owncloud_download|changed

- name: ensure writable directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
    mode: "u=rwX,g=rX,o=rX"
    recurse: yes
  with_items:
    - /var/www/owncloud/apps
    - /var/www/owncloud/apps-store
    - /var/www/owncloud/themes
    - /var/www/owncloud/assets

- name: ensure private directories have correct owners
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: apache
    recurse: yes
  with_items:
    - "{{ owncloud_data_directory }}"
    - /etc/owncloud

- name: ensure private directories have correct permissions
  file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o-rwx"
  with_items:
    - "{{ owncloud_data_directory }}"
    - /etc/owncloud

- name: check config directory
  stat:
    path: /var/www/owncloud/config
  register: owncloud_config_directory

- name: ensure config directory is removed
  file:
    path: /var/www/owncloud/config
    state: absent
  when: owncloud_config_directory.stat.islnk == false

- name: ensure default data directory is removed
  file:
    path: /var/www/owncloud/data
    state: absent

- name: ensure config directory is linked from /etc
  file:
    src: /etc/owncloud
    dest: /var/www/owncloud/config
    state: link
    force: yes
