---
- include_vars: "{{ owncloud_vendor }}.yml"
- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: define version
  set_fact:
    owncloud_version: "{% if owncloud_vendor == 'nextcloud' %}12.0.1{% else %}10.0.2{% endif %}"
  when: not owncloud_version

- name: ensure required packages are installed
  package:
    name: "{{ item }}"
  with_items:
    - tar
    - bzip2

- name: ensure application is downloaded
  unarchive:
    src: "{{ owncloud_source_url }}"
    dest: /var/www
    owner: "{{ owncloud_webserver_user }}"
    group: "{{ owncloud_webserver_group }}"
    mode: "u=rwX,g=rX,o=rX"
    copy: no
    creates: "{{ owncloud_destination }}"
  register: owncloud_download

- name: ensure config directory exists
  file:
    path: "{{ owncloud_config_directory }}"
    state: directory
    owner: "{{ owncloud_webserver_user }}"
    group: "{{ owncloud_webserver_group }}"
    mode: 0755

- name: ensure data directory exists
  file:
    path: "{{ owncloud_data_directory }}"
    state: directory
    owner: "{{ owncloud_webserver_user }}"
    group: "{{ owncloud_webserver_group }}"
    mode: 0770

- name: ensure owncloud is configured
  template:
    src: custom.config.php.j2
    dest: "{{ owncloud_config_directory }}/custom.config.php"
    owner: "{{ owncloud_webserver_user }}"
    group: "{{ owncloud_webserver_group }}"
    mode: 0640

- name: check original config directory
  stat:
    path: "{{ owncloud_destination }}/config"
  register: owncloud_original_config_directory

- name: ensure original config directory is removed
  file:
    path: "{{ owncloud_destination }}/config"
    state: absent
  when: owncloud_original_config_directory.stat.exists and owncloud_original_config_directory.stat.islnk == false

- name: ensure config directory is linked from /etc
  file:
    src: "{{ owncloud_config_directory }}"
    dest: "{{ owncloud_destination }}/config"
    state: link
    force: yes

- name: check original data directory
  stat:
    path: "{{ owncloud_destination }}/data"
  register: owncloud_original_data_directory

- name: ensure original data directory is removed
  file:
    path: "{{ owncloud_destination }}/data"
    state: absent
  when: owncloud_original_data_directory.stat.exists and owncloud_original_data_directory.stat.islnk == false

- name: ensure data directory is linked
  file:
    src: "{{ owncloud_data_directory }}"
    dest: "{{ owncloud_destination }}/data"
    state: link
    force: yes

- include: webserver/nginx_conf.yml
  when: ansible_os_family == 'RedHat'

- include: webserver/nginx_sites.yml
  when: ansible_os_family == 'Debian'

- include: database/mysql.yml
  when: owncloud_database_server == 'mysql'

- include: install.yml
- include: apps.yml

- include: timer/cron.yml
  when: ansible_service_mgr != 'systemd'

- include: timer/systemd.yml
  when: ansible_service_mgr == 'systemd'
